-  name: Force Ansible to use Python 3.9
   ansible.builtin.set_fact:
     ansible_python_interpreter: /usr/bin/python3.9

-  name: Set Prompt
   ansible.builtin.shell: set-prompt grafana


-  name: Copy grafana repo file
   ansible.builtin.template:
     src: grafana.repo
     dest: /etc/yum.repos.d/grafana.repo

-  name: Installed the grafana
   ansible.builtin.dnf:
     name: grafana
     state: installed

-  name: Copy datasource (pom-datasource.yml)
   ansible.builtin.template:
     src: pom-datasource.yml
     dest: /etc/grafana/provisioning/datasources/pom-datasource.yml

-  name: Copy dashboard jason file
   ansible.builtin.template:
     src: sample-dashboard.json
     dest: /etc/grafana/provisioning/dashboards/sample-dashboard.json

#-  name: import dashboard
#   community.general.grafana_dashboard:
#     url:
#     login_user: admin
#     login_password:
#     state: present
#     commit_message: "update by ansible"
#     overwrite: true
#     path: /tmp/sample-dashboard.json


-  name: Import Grafana dashboard
   community.grafana.grafana_dashboard:
     grafana_url: http://localhost:3000
     grafana_user: "admin"
     grafana_password: "Saira@123"
     state: present
     commit_message: Updated by ansible
     overwrite: true
     path: /tmp/sample-dashboard.json




-  name: Start grafana service
   ansible.builtin.systemd_service:
     state: started
     daemon_reload: true
     name: grafana-server
     enabled: yes