-  name: Force Ansible to use Python 3.9
   ansible.builtin.set_fact:
     ansible_python_interpreter: /usr/bin/python3.9

-  name: Set Prompt
   ansible.builtin.shell: set-prompt Ci-server


-  name: Create runner directory
   ansible.builtin.file:
     state: directory
     path: /home/ec2-user/github-runner
   become_user: ec2-user

-  name: Download and extract the runner content
   ansible.builtin.unarchive:
     src: https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
     dest: /home/ec2-user
     remote_src: yes
   become_user: ec2-user

-  name: Install Dependencies
   ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh

- name: Start Runner
  ansible.builtin.shell: ./svc.sh install; ./svc.sh start
  args:
    chdir: /home/ec2-user/github-runner