-  name: Force Ansible to use Python 3.9
   ansible.builtin.set_fact:
     ansible_python_interpreter: /usr/bin/python3.9

-  name: Set Prompt
   ansible.builtin.shell: set-prompt Ci-server


#-  name: Uninstall  Runner
#   ansible.builtin.shell: ./svc.sh uninstall
#   args:
#     chdir: /home/ec2-user/github-runner

-  name: Stop runner service
   ansible.builtin.shell: ./svc.sh stop
   args:
     chdir: /home/ec2-user/github-runner
   ignore_errors: yes

-  name: Uninstall runner service
   ansible.builtin.shell: ./svc.sh uninstall
   args:
     chdir: /home/ec2-user/github-runner
   ignore_errors: yes

-  name: Remove old runner config files
   ansible.builtin.file:
     path: "{{ item }}"
     state: absent
   loop:
     - /home/ec2-user/github-runner/.runner
     - /home/ec2-user/github-runner/.credentials
     - /home/ec2-user/github-runner/.credentials_rsaparams
   ignore_errors: yes


-  name: Download and extract the runner content
   ansible.builtin.unarchive:
     src: https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
     dest: /home/ec2-user/github-runner
     remote_src: yes
   become_user: ec2-user

-  name: Install Dependencies
   ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh

#-  name: Install Runnner
#   ansible.builtin.shell: ./config.sh remove --token {{secrets.Github_Runner_Token}}; ./config.sh --unattended --url https://github.com/awsdevops-sbs --token {{secrets.Github_Runner_Token}}
#   args:
#     chdir: /home/ec2-user/github-runner
#   become_user: ec2-user

#-  name: Remove existing runner
#   ansible.builtin.shell: ./config.sh remove --token {{ secrets.Github_Runner_Token }}
#   args:
#     chdir: /home/ec2-user/github-runner
#   become_user: ec2-user
#   ignore_errors: yes
#
#-  name: Remove existing runner
#   ansible.builtin.shell: ./config.sh remove --token {{ secrets.Github_Runner_Token }}
#   args:
#     chdir: /home/ec2-user/github-runner
#   become_user: ec2-user
#   ignore_errors: yes

-  name: Configure runner
   ansible.builtin.shell: >
     ./config.sh remove --token {{secrets.Github_Runner_Token}}
     ./config.sh --unattended
     --url https://github.com/awsdevops-sbs
     --token {{ secrets.Github_Runner_Token }}
   args:
     chdir: /home/ec2-user/github-runner
   become_user: ec2-user




-  name: Start Runner service
   ansible.builtin.shell: ./svc.sh install; ./svc.sh start
   args:
     chdir: /home/ec2-user/github-runner



-  name: Disable default Nodejs version
   ansible.builtin.shell: dnf module disable nodejs -y

-  name: Enable nodejs module for v20
   ansible.builtin.shell: dnf module enable nodejs:20 -y


-  name: Install NodeJS
   ansible.builtin.dnf:
     name: nodejs
     state: installed

-  name: Install Java
   ansible.builtin.dnf:
     name: java-17-openjdk
     state: installed

-  name: Download sonar scanner
   ansible.builtin.unarchive:
     src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
     dest: /opt
     remote_src: yes

