#vault_token: "{{ lookup('ansible.builtin.env', 'vault_token') }}"
#secrets: "{{lookup('hashi_vault', 'secret=Ci_server/data/CI_secret token={{ vault_token }} http://vault.awsdevops16297.sbs:8200 validate_certs=False')}}"

vault_token: "{{ lookup('ansible.builtin.env', 'vault_token') }}"

secrets: "{{ lookup('community.hashi_vault.hashi_vault',
  'secret=Ci_server/data/CI_secret token=' ~ vault_token ~
  ' url=http://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"