format_version: 10
pipelines:
  grafana:
    group: tools
    materials:
      git-5766e3f:
        git: https://github.com/awsdevops-sbs/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:U0sg7KpcTxZAEdlnMlpDMA==:FxINJdICkPIxs4AVfMQTnnvCWikRpol5GDGrk6szHpg=
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i","grafana-internal.awsdevops16297.sbs,","-e","ansible_user=ec2-user","-e","ansible_password=DevOps321","-e","tool_name=grafana","tools.yml"] , run_if: passed }






