format_version: 10
pipelines:
  tools-tf-apply:
    group: terraform
    materials:
      git-5766e3f:
        git: https://github.com/awsdevops-sbs/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Dev:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
           terraform-apply:
             tasks:
             - exec: {command: terraform, arguments: [ "init"] , run_if: passed }
             - exec: {command: terraform, arguments: [ "apply", "-auto-approve"], run_if: passed }





