apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.awsdevops16297.sbs:9090/

    jsonData:
      httpMethod: POST
      manageAlters: true
      prometheusType: Prometheus
      cacheLevel: 'low'