#- name: Force Ansible to use Python 3.9
#  ansible.builtin.set_fact:
#    ansible_python_interpreter: /usr/bin/python3.9
#
#- name: Set Prompt
#  ansible.builtin.shell: set-prompt Artifactory
#
#- name: Copy artifactory repo file
#  ansible.builtin.template:
#    src: jfrog.repo
#    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo
#
#- name: Install artifactory and PostgreSQL
#  ansible.builtin.dnf:
#    name: [jfrog-artifactory-oss-7.77.14, postgresql-server, python3-psycopg2]
#    state: installed
#    disable_gpg_check: true
#
#- name: Setup PostgreSQL
#  ansible.builtin.shell: |
#    postgresql-setup --initdb || true
#    sed -i 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf
#    systemctl start postgresql
#    sudo -u postgres psql -c "CREATE USER artifactory WITH PASSWORD 'artifactory';" || true
#    sudo -u postgres psql -c "CREATE DATABASE artifactory OWNER artifactory;" || true
#
#- name: Configure Artifactory system.yaml
#  ansible.builtin.copy:
#    dest: /opt/jfrog/artifactory/var/etc/system.yaml
#    owner: artifactory
#    group: artifactory
#    content: |
#      shared:
#        database:
#          driver: org.postgresql.Driver
#          type: postgresql
#          url: "jdbc:postgresql://localhost:5432/artifactory"
#          username: artifactory
#          password: artifactory
#
#- name: Start Artifactory
#  ansible.builtin.systemd_service:
#    name: artifactory
#    state: started
#    daemon_reload: true
#    enabled: yes






- name: Force Ansible to use Python 3.9
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/bin/python3.9

- name: Set Prompt
  ansible.builtin.shell: set-prompt Artifactory

- name: Copy artifactory repo file
  ansible.builtin.template:
    src: jfrog.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo

- name: Install artifactory and PostgreSQL
  ansible.builtin.shell: |
    dnf clean all
    rm -rf /var/cache/dnf/*
    find /var/log -name "*.log" -mtime +1 -exec truncate -s 0 {} \;
    dnf install -y jfrog-artifactory-oss-7.77.14 postgresql-server python3-psycopg2 --nogpgcheck


- name: Setup PostgreSQL
  ansible.builtin.shell: |
    postgresql-setup --initdb || true
    sed -i 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf
    systemctl start postgresql
    sudo -u postgres psql -c "CREATE USER artifactory WITH PASSWORD 'artifactory';" || true
    sudo -u postgres psql -c "CREATE DATABASE artifactory OWNER artifactory;" || true

- name: Configure Artifactory system.yaml
  ansible.builtin.copy:
    dest: /opt/jfrog/artifactory/var/etc/system.yaml
    owner: artifactory
    group: artifactory
    content: |
      shared:
        database:
          driver: org.postgresql.Driver
          type: postgresql
          url: "jdbc:postgresql://localhost:5432/artifactory"
          username: artifactory
          password: artifactory

- name: Start Artifactory
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    daemon_reload: true
    enabled: yes